import Header from '@/Components/Header'
import './globals.css'

export const metadata = {
  title: 'App de pruebas', 
  description: 'Generated by Cecilia Perdomo',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        </body>
    </html>
  )
}
